name: build_readme

on:
  push:
    paths-ignore:
      - '*.md'

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  compile_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          persist-credentials: false

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Generate from stub
        run: python utils/stub_handler.py || echo "Stub generation failed."

      - name: Commit files
        run: |
          git config --local user.email "johannes@stenmark.in"
          git config --local user.name "JStenmark"
          git add *.md
          git commit -m "CI: Updated content" || echo "Nothing to commit."

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          force: true
